unicef/etools-psea

src_ts/components/app-shell/app-shell.ts
=> Fixed Follow-up tab display

src_ts/components/app-shell/app-shell.ts, src_ts/components/common-data/common-data-actions.ts, src_ts/components/common-data/common-data.ts, src_ts/endpoints/endpoints-list.ts, src_ts/redux/actions/common-data.ts, src_ts/redux/reducers/common-data.ts, src_ts/redux/store.ts, src_ts/types/globals.ts
added unicefUsers commonData to redux
=> added unicefUsers commonData to redux

src_ts/components/common/layout/etools-tabs.ts, src_ts/components/common/layout/status/etools-status.ts, src_ts/components/common/layout/support-btn.ts, src_ts/components/common/toast-notifications/etools-toast.ts
Converted `etools-tabs`, `support-btn`, `etools-status`, `etools-toast` to LitElement
=> Convert components to LitElement

src_ts/components/common/layout/status/etools-status.ts, src_ts/components/common/layout/status/status-icons.ts, src_ts/components/common/toast-notifications/etools-toast.ts
Fixes after converting to LitElement
=> Fix convert litelement

src_ts/components/common/toast-notifications/etools-toast.ts
Updated toast to autoclose even if showCloseBtn property is not set.
=> Toast improvement

images/required.svg, src_ts/components/pages/engagements/engagement-tab-pages/details/external-individual.ts, src_ts/components/pages/engagements/engagement-tab-pages/details/firm-staff-members.ts, src_ts/components/pages/engagements/engagement-tab-pages/details/staff-member-dialog.ts, src_ts/components/pages/engagements/engagement-tab-pages/details/staff-member.ts, src_ts/components/pages/engagements/engagement-tab-pages/details/unicef-staff-assessor.ts, src_ts/components/styles/shared-styles-lit.ts, src_ts/components/user/user-model.ts, src_ts/endpoints/endpoints-list.ts
Added dialog for add/update Staff members and External individuals
=> Staff member dialog

images/required.svg, src_ts/components/pages/engagements/engagement-tab-pages/details/assessing-firm.ts, src_ts/components/pages/engagements/engagement-tab-pages/details/assessor-info.ts, src_ts/components/pages/engagements/engagement-tab-pages/details/engagement-details-page.ts, src_ts/components/pages/engagements/engagement-tab-pages/details/firm-staff-members.ts, src_ts/components/pages/engagements/engagement-tab-pages/details/staff-member-dialog.ts, src_ts/endpoints/endpoints-list.ts
Assessing firm - Enter po number
=> Assessing firm - Enter po number

src_ts/components/pages/engagements/engagement-tab-pages/details/assessing-firm.ts, src_ts/components/pages/engagements/engagement-tab-pages/details/firm-staff-members.ts
Assessing fixes in case order number it's not valid
=> Assessing fixes in case order number it's not valid

src_ts/components/app-shell/app-shell.ts, src_ts/components/app-shell/app-theme.ts, src_ts/components/app-shell/header/countries-dropdown-styles.ts, src_ts/components/common-data/common-data.ts, src_ts/components/pages/engagements/engagement-tab-pages/details/assessing-firm.ts, src_ts/components/pages/engagements/engagement-tab-pages/details/assessment-info.ts, src_ts/components/pages/engagements/engagement-tab-pages/details/assessor-info.ts, src_ts/components/pages/engagements/engagement-tab-pages/details/engagement-details-page.ts, src_ts/components/pages/engagements/engagement-tab-pages/details/external-individual.ts, src_ts/components/pages/engagements/engagement-tab-pages/details/firm-staff-members.ts, src_ts/components/pages/engagements/engagement-tab-pages/details/partner-details.ts, src_ts/components/pages/engagements/engagement-tab-pages/details/staff-member-dialog.ts, src_ts/components/pages/page-not-found.ts, src_ts/components/styles/grid-layout-styles-lit.ts, src_ts/components/styles/label-and-value-styles-lit.ts, src_ts/components/styles/shared-styles-lit.ts, src_ts/components/user/etools-user.ts, src_ts/components/utils/ajax-error-parser.ts, src_ts/components/utils/request-helper.ts, src_ts/endpoints/endpoints-list.ts, src_ts/endpoints/endpoints.ts, src_ts/redux/actions/common-data.ts, src_ts/redux/reducers/common-data.ts, src_ts/types/engagement.ts
Left to do(on different PR) -handle edit order number
=> Create edit assessor

src_ts/components/app-shell/app-shell.ts, src_ts/components/app-shell/app-theme.ts, src_ts/components/pages/engagements/engagement-tab-pages/details/staff-member-dialog.ts
Not Found page was not displayed
Staff member dialog layout tweaks
=> Fixes on Not found page and Staff member dialog

src_ts/components/app-shell/app-shell.ts, src_ts/components/pages/engagements/engagement-tab-pages/details/assessment-info.ts, src_ts/components/pages/engagements/engagement-tabs.ts, src_ts/redux/actions/page-data.ts, src_ts/redux/reducers/page-data.ts, src_ts/redux/store.ts
Added redux for current assessment, updated engagement tabs
=> Added redux for current assessment & show page title

src_ts/components/app-shell/app-theme.ts
=> Fixed profile dialog layout

src_ts/components/pages/engagements/engagement-tab-pages/details/assessment-info.ts, src_ts/components/pages/engagements/engagement-tabs.ts, src_ts/redux/reducers/page-data.ts
Get assessment info on engagement-tabs
=> Get Assessment info on engagement-tabs

src_ts/components/pages/assessments/assessment-tab-pages/details/external-individual-dialog.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/staff-member-dialog.ts
[ch14543] External Assessor - make sure toast msg are displayed in case the new entered external individual exists/has unicef.org email.
=> [ch14543] External Assessor - validate external individual

src_ts/components/pages/assessments/list/filters.ts
[ch14613] Update filter statuses
=> [ch14613] Update filter statuses

src_ts/components/pages/assessments/assessments-list.ts, src_ts/components/user/etools-user.ts, src_ts/components/user/user-model.ts, src_ts/redux/actions/user.ts, src_ts/redux/reducers/user.ts
[ch14562] Only unicef user and unicef focal point can add new assessment
=> [ch14562] Only unicef user and unicef focal point can add new assessment

src_ts/components/pages/assessments/assessments-list.ts
=> List- update Rating column

src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/assessment-questionnaire-page.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/questionnaire-item.ts, src_ts/components/pages/assessments/assessments-list.ts
=> Handle display of overall_rating once all answers provided

src_ts/components/pages/assessments/assessments-list.ts
[ch14748] Some filters not populated after page refresh
=> [ch14748] Some filters not populated after page refresh

src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/questionnaire-answer.ts
[ch14695] Questionnaire - Other evidence input issue
=> [ch14695] Questionnaire - Other evidence input issue

src_ts/components/pages/assessments/assessment-tab-pages/details/staff-member-dialog.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/assessment-questionnaire-page.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/questionnaire-item.ts, src_ts/types/assessment.ts
=> Handle Questionnaire permissions

src_ts/components/pages/assessments/assessment-tab-pages/details/assessment-info.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/assessor-info.ts
=> Fix edit assessment info & handle err on edit assessor

src_ts/components/pages/assessments/assessment-tab-pages/follow-up/follow-up-dialog.ts
=> Resets dialog data when dialog is closed

src_ts/components/pages/assessments/assessment-tab-pages/follow-up/follow-up-page.ts
=> Removes right/left padding from follow up list table

src_ts/components/pages/assessments/assessment-tab-pages/details/assessor-info.ts
[ch14864] Selected external individual is cleared
=> [ch14864] Selected external individual is cleared

src_ts/components/common/layout/etools-table/etools-table-styles.ts, src_ts/components/common/layout/etools-table/etools-table.ts, src_ts/components/pages/assessments/assessment-status-transition-actions.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/assessment-info.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/assessor-info.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/firm-staff-members.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/questionnaire-answer.ts, src_ts/components/pages/mixins/permissions-mixins.ts, src_ts/types/assessment.ts
=> Assessment details permissions

src_ts/components/pages/assessments/assessment-tab-pages/follow-up/follow-up-dialog.ts, src_ts/components/pages/assessments/assessment-tab-pages/follow-up/follow-up-page.ts
=> Update copy warning

src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/assessment-questionnaire-page.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/questionnaire-item.ts, src_ts/components/utils/fire-custom-event.ts, src_ts/types/assessment.ts
=> Fix re-render issues with repeated components(cancel issue on question)

src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/questionnaire-item.ts, src_ts/components/styles/radio-button-styles.ts
Questionnaire header layout fixes
=> [ch14905] Handle overflow of question title

src_ts/components/common/layout/etools-table/etools-table.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/assessor-info.ts, src_ts/components/pages/assessments/assessment-tab-pages/follow-up/follow-up-page.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/assessment-questionnaire-page.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/questionnaire-item.ts, src_ts/components/pages/assessments/assessments-list.ts, src_ts/components/pages/assessments/list/filters.ts
[ch15094] PSEA Pre deployment Bug Fixes and features
=> [ch15094] PSEA Pre deployment Bug Fixes and features

src_ts/components/app-shell/app-shell.ts, src_ts/components/common/environment-flags.ts, src_ts/endpoints/endpoints-list.ts
[ch14865] Condition display of PSEA app content by environment flag
=> [ch14865] Condition display of PSEA app content by environment flag

src_ts/components/common/environment-flags.ts
Modified conditional display warning message
=> Modified conditional display warning message

package-lock.json, package.json
=> Upgrades etools-app-selector to v3.1.0

src_ts/components/common/layout/etools-table/etools-table.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/assessment-info.ts, src_ts/components/pages/assessments/assessment-tab-pages/follow-up/follow-up-page.ts
Loading Focal Point users refactoring and message
Renamed table column property
=> Small refactoring

package-lock.json, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/assessment-questionnaire-page.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/questionnaire-answer.ts
=> Fix overall rating refresh

src_ts/components/common/common-methods.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/assessor-info.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/assessment-questionnaire-page.ts, src_ts/components/pages/assessments/assessment-tabs.ts, src_ts/redux/actions/page-data.ts
=> [ch15381]Fix update permissions after assessor save

src_ts/components/app-shell/app-shell.ts, src_ts/components/app-shell/menu/app-menu.ts, src_ts/components/pages/assessments/assessments-list.ts, src_ts/redux/actions/app.ts, src_ts/routing/router.ts, src_ts/routing/routes.ts, src_ts/routing/subpage-redirect.ts
=> [ch15550]Fixes for navigate back

package-lock.json, package.json, src_ts/components/app-shell/app-shell.ts, src_ts/components/common/common-methods.ts, src_ts/components/common/environment-flags.ts, src_ts/components/common/layout/etools-table/etools-table-utility.ts, src_ts/components/common/layout/filters/etools-filters.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/assessing-firm.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/assessment-info.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/assessor-info.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/firm-staff-members.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/partner-details.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/staff-member-dialog.ts, src_ts/components/pages/assessments/assessment-tab-pages/follow-up/follow-up-page.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/assessment-questionnaire-page.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/questionnaire-answer.ts, src_ts/components/pages/assessments/assessment-tabs.ts, src_ts/components/pages/assessments/assessments-list.ts, src_ts/components/pages/assessments/list/filters.ts, src_ts/components/pages/assessments/status-transitions/assessment-status-transition-actions.ts, src_ts/components/user/user-actions.ts, src_ts/redux/actions/app.ts, src_ts/redux/actions/common-data.ts, src_ts/redux/actions/page-data.ts, src_ts/types/assessment.ts
=> [ch15738] member needs to be removed & lint & [ch16010] logs fixes

src_ts/components/pages/assessments/assessment-tab-pages/details/assessing-firm.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/assessor-info.ts
=> Fix display of get firm details warning on cancel edit

src_ts/components/common/layout/filters/etools-filters.ts, src_ts/components/pages/assessments/assessments-list.ts
[ch15776] Filtering issue while on greater page than 1
=> [ch15776] Filtering issue while on greater page than 1

src_ts/components/pages/assessments/list/filters.ts, src_ts/components/pages/assessments/status-transitions/assessment-rejection-dialog.ts
=> Fix  assessment date filter show

src_ts/components/common/layout/etools-error-warn-box.ts, src_ts/components/common/layout/filters/etools-filters.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/assessing-firm.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/assessment-details-page.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/assessment-info.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/assessor-info.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/external-individual-dialog.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/external-individual.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/partner-details.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/staff-member-dialog.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/answer-instructions.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/question-attachments.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/questionnaire-answer.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/questionnaire-item.ts, src_ts/components/pages/assessments/assessment-tabs.ts, src_ts/components/pages/assessments/assessments-list.ts, src_ts/components/pages/assessments/status-transitions/assessment-status-transition-actions.ts, src_ts/components/pages/page-not-found.ts, src_ts/components/styles/button-styles.ts, src_ts/components/styles/label-and-value-styles-lit.ts, src_ts/components/styles/page-layout-styles.ts, src_ts/components/styles/radio-button-styles.ts
=> [ch15783]Styles optimization

src_ts/components/pages/assessments/assessment-tab-pages/details/assessment-info.ts
=> [ch15946]Do not allow assessment date in the future

src_ts/components/common/common-methods.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/assessment-info.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/external-individual.ts, src_ts/components/pages/assessments/list/filters.ts
=> [ch15685]Fix selected external not shown when logged in as external user

src_ts/components/common/layout/etools-table/etools-table-utility.ts, src_ts/components/pages/assessments/assessments-list.ts
=> [ch16102] Fix filter issues on navigation between pages

src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/questionnaire-answer.ts
adjusted error message font-size
=> [ch16100] Answer radio group validation should be updated

src_ts/components/pages/assessments/assessments-list.ts, src_ts/components/pages/assessments/list/filters.ts, src_ts/redux/actions/common-data.ts
=> [ch16178]Fix no filter available when logged in as external

src_ts/components/common/layout/etools-table/etools-table-styles.ts, src_ts/components/common/layout/export-data.ts, src_ts/components/common/layout/filters/etools-filters.ts, src_ts/components/styles/lit-styles/elevation-styles.ts
added accessibility specific styles
=> [ch16190] Accessibility- Emphasize focused fields on list

package-lock.json, package.json
=> Update package-lock for etools-dropdown

src_ts/components/pages/assessments/assessment-tab-pages/details/external-individual.ts
[ch15740] Name and email id should be displayed whenever external member is selected
showing email of the selected external-individual
=> [ch15740] Name and email id should be displayed whenever external member is selected

src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/questionnaire-item.ts
=> [ch16596]Show loading on Save questionnaire-item

src_ts/components/pages/assessments/assessment-tab-pages/details/assessor-info.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/external-individual.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/question-attachments.ts
=> [ch17130]Fix navigation between assessments with external assessor

package-lock.json, src_ts/components/app-shell/app-shell.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/assessor-info.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/external-individual.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/assessment-questionnaire-page.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/question-attachments.ts, src_ts/components/pages/assessments/assessment-tabs.ts, src_ts/redux/actions/app.ts, src_ts/redux/actions/page-data.ts, src_ts/redux/reducers/page-data.ts, src_ts/routing/router.ts
=> [ch17059]Avoid unnecessary Api call & [ch16738] Export btn intermittent visibility

package.json, src_ts/components/app-shell/app-shell-styles.ts, src_ts/components/app-shell/footer/page-footer.ts, src_ts/components/app-shell/header/page-header-styles.ts, src_ts/components/app-shell/menu/styles/nav-menu-styles.ts, src_ts/components/common/layout/etools-error-warn-box.ts, src_ts/components/common/layout/etools-table/etools-table-styles.ts, src_ts/components/common/layout/etools-table/pagination/etools-pagination-style.ts, src_ts/components/common/layout/etools-tabs.ts, src_ts/components/common/layout/page-content-header/page-content-header-slotted-styles.ts, src_ts/components/common/layout/page-content-header/page-content-header.ts, src_ts/components/common/layout/status/etools-status.ts, src_ts/components/common/toast-notifications/etools-toast.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/assessing-firm.ts, src_ts/components/styles/grid-layout-styles-lit.ts
=> Removed lit-flexbox-literals

src_ts/components/pages/assessments/assessments-list.ts
[ch17314] Remove the add button for users that are not Audit Focal Point
=> [ch17314] Remove the add button for users that are not Audit Focal Point

src_ts/components/app-shell/menu/app-menu.ts
[ch16240] PSEA: Menu header name.
=> [ch16240] PSEA: Menu header name.

src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/question-attachments.ts
[ch17177] File Attachment with long name escapes page
=> [ch17177] File Attachment with long name escapes page

src_ts/components/pages/assessments/assessment-tabs.ts
[ch16738] PSEA: Export btn intermittent visibility
=> [ch16738] PSEA: Export btn intermittent visibility

package.json, src_ts/components/app-shell/header/countries-dropdown-styles.ts, src_ts/components/app-shell/header/page-header-styles.ts
[ch17296] Responsive app header
=> [ch17296] Responsive app header

src_ts/components/pages/assessments/assessment-tab-pages/follow-up/follow-up-dialog.ts
[ch17398] PSEA: Console error on Refresh Follow-up page
=> [ch17398] PSEA: Console error on Refresh Follow-up page

src_ts/components/app-shell/header/countries-dropdown-styles.ts, src_ts/components/app-shell/header/page-header-styles.ts, src_ts/components/common/layout/etools-table/etools-table-responsive-styles.ts, src_ts/components/common/layout/etools-table/etools-table-styles.ts, src_ts/components/common/layout/etools-table/pagination/etools-pagination-style.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/firm-staff-members.ts, src_ts/components/pages/assessments/assessments-list.ts, src_ts/components/styles/page-layout-styles.ts
[ch17380] FM offline -Improve list responsiveness
=> [ch17380] FM offline -Improve list responsiveness

src_ts/components/pages/assessments/assessments-list.ts
[ch17399] PSEA: Add loading spinner for filters
=> [ch17399] PSEA: Add loading spinner for filters

src_ts/components/pages/assessments/assessment-tab-pages/details/assessing-firm.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/assessment-info.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/assessor-info.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/external-individual-dialog.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/external-individual.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/firm-staff-members.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/partner-details.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/staff-member-dialog.ts, src_ts/components/pages/assessments/assessment-tab-pages/follow-up/follow-up-dialog.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/assessment-questionnaire-page.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/question-attachments.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/questionnaire-answer.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/questionnaire-item.ts, src_ts/components/pages/page-not-found.ts, src_ts/components/styles/grid-layout-styles-lit.ts, src_ts/components/styles/lit-styles/flex-layout-styles.ts, src_ts/redux/actions/app.ts
=> [ch16743]Convert grid-layout-styles to lit static styles

src_ts/components/common/environment-flags.ts
[ch16973] PSEA: Not redirected to '/landing' page when not authenticated
=> [ch16973] PSEA: Not redirected to '/landing' page when not authenticated

src_ts/components/common/layout/filters/etools-filters-styles.ts, src_ts/components/common/layout/page-content-header/page-content-header-slotted-styles.ts, src_ts/components/common/layout/page-content-header/page-content-header.ts, src_ts/components/pages/assessments/assessments-list.ts, src_ts/components/styles/page-layout-styles.ts
[ch17340] Responsive filter section
=> [ch17340] Responsive filter section

src_ts/components/pages/assessments/assessment-tab-pages/details/assessment-info.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/assessor-info.ts, src_ts/components/pages/assessments/assessment-tabs.ts
[ch 17401] PSEA: Loading not shown on refresh assessment details page
=> [ch 17401] PSEA: Loading not shown on refresh assessment details page

src_ts/components/app-shell/app-shell.ts, src_ts/components/pages/assessments/assessments-list.ts
=> [ch17555]Fix perpetual spin for external

polymer.json, src_ts/components/app-shell/app-shell-styles.ts, src_ts/components/app-shell/app-shell.ts, src_ts/components/app-shell/footer/page-footer.ts, src_ts/components/app-shell/header/page-header-styles.ts, src_ts/components/app-shell/header/page-header.ts, src_ts/components/app-shell/menu/app-menu.ts, src_ts/components/app-shell/menu/styles/app-drawer-styles.ts, src_ts/components/app-shell/menu/styles/nav-menu-styles.ts, src_ts/components/common/layout/etools-error-warn-box.ts, src_ts/components/common/layout/etools-table/etools-table-responsive-styles.ts, src_ts/components/common/layout/etools-table/etools-table-styles.ts, src_ts/components/common/layout/etools-table/etools-table.ts, src_ts/components/common/layout/etools-table/pagination/etools-pagination-style.ts, src_ts/components/common/layout/etools-table/pagination/etools-pagination.ts, src_ts/components/common/layout/etools-tabs.ts, src_ts/components/common/layout/page-content-header/page-content-header-slotted-styles.ts, src_ts/components/common/layout/page-content-header/page-content-header.ts, src_ts/components/common/layout/status/etools-status.ts, src_ts/components/common/toast-notifications/etools-toast.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/assessing-firm.ts, src_ts/components/styles/grid-layout-styles-lit.ts, src_ts/components/styles/lit-styles/flex-layout-styles.ts
[ch17147] PSEA: new opportunity to switch to static styles
=> [ch17147] PSEA: new opportunity to switch to static styles

src_ts/components/pages/assessments/status-transitions/assessment-status-transition-actions.ts
[ch17733] PSEA: I can press the same status transition button 2 times
=> [ch17733] PSEA: I can press the same status transition button 2 times

package-lock.json, package.json, src_ts/components/app-shell/app-shell.ts, src_ts/components/user/user-actions.ts
[ch16003] Drop-down Search not tied to search input
=> [ch16003] Drop-down Search not tied to search input

package-lock.json, package.json, src_ts/components/pages/assessments/assessment-tab-pages/details/firm-staff-members.ts, src_ts/components/pages/assessments/assessments-list.ts
[ch17815] Replace local etools-table with the one from npm package
=> [ch17815] Replace local etools-table with the one from npm package

src_ts/components/pages/assessments/assessment-tab-pages/details/assessor-info.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/external-individual.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/firm-staff-members.ts
=> [ch18264] Assessor Errors

src_ts/components/app-shell/app-theme.ts
=> [ch18309] Fix divider color

package-lock.json, src_ts/components/app-shell/app-shell.ts, src_ts/components/pages/assessments/assessment-tab-pages/follow-up/follow-up-dialog.ts
=> [ch17438]Datepicker cut off fix

src_ts/components/pages/assessments/assessment-tabs.ts
[ch19403] Console error on refresh Follow-up page
=> [ch19403] Console error on refresh Follow-up page

src_ts/components/pages/assessments/assessment-tab-pages/details/assessment-info.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/assessor-info.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/firm-staff-members.ts, src_ts/components/pages/assessments/assessments-list.ts, src_ts/types/assessment.ts, src_ts/types/user-model.ts
[ch19956] Frontend linting fixes
=> [ch19956] Frontend linting fixes

src_ts/components/styles/shared-styles-lit.ts
[ch20766] Cannot scroll on dialog
=> [ch20766] Cannot scroll on dialog

src_ts/components/styles/shared-styles-lit.ts
[ch20999] Cannot add Comments/Other in Questionnaire
=> [ch20999] Cannot add Comments/Other in Questionnaire

src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/questionnaire-item.ts
=> page reload after save

src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/questionnaire-item.ts
[ch21670] Hotfix upload issue in PSEA
=> [ch21670] Hotfix upload issue in PSEA

src_ts/components/utils/date-utility.ts
=> [ch22995]Error on upload attachment in questionnaire

src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/question-attachments.ts
=> [ch22995]Extra checks for valid response from bk on uploaded file 

src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/assessment-questionnaire-page.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/question-attachments.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/questionnaire-answer.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/questionnaire-item.ts
=> [ch23305]Fix inconsistencies on upload

src_ts/components/common/layout/are-you-sure.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/question-attachments.ts, src_ts/components/utils/dialog.ts, src_ts/types/dialog.ts
[ch23620] Show confirmation dialog on delete saved attachment
=> [ch23620] Show confirmation dialog on delete saved attachment

src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/assessment-questionnaire-page.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/question-attachments.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/questionnaire-answer.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/questionnaire-item.ts
=> [ch24126]Fix save after upload

src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/assessment-questionnaire-page.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/question-attachments.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/questionnaire-answer.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/questionnaire-item.ts
* Fix save after upload
* Fix invalid validation msg on file type
* Fix file not reset on cancel
* uncomment
=> [ch24126]Fix save after upload (#290)

src_ts/components/styles/shared-styles-lit.ts
[ch24784] Black border if you click near Please specify Other in Questionnaire
=> [ch24784] Black border if you click near Please specify Other in Questionnaire

src_ts/components/pages/assessments/assessment-tabs.ts, src_ts/components/pages/assessments/status-transitions/assessment-status-transition-actions.ts
[ch24746] Background is not entirely blurred when saving sections on form
=> [ch24746] Background is not entirely blurred when saving sections on form

src_ts/components/pages/assessments/assessment-tabs.ts
[ch24978] 'Loading..' display issue
=> [ch24978] 'Loading..' display issue

src_ts/components/pages/assessments/list/filters.ts
[ch24601] Assessment Date filter not working
=> [ch24601] Assessment Date filter not working

src_ts/components/pages/assessments/assessment-tab-pages/details/assessment-info.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/partner-details.ts
[ch18403] Add more details to the PSEA details screen.
=> [ch18403] Add more details to the PSEA details screen.

src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/assessment-questionnaire-page.ts
[ch25128] Previous navigation view is kept on a new assessment questionnaire
=> [ch25128] Previous navigation view is kept on a new assessment questionnaire

src_ts/components/common/layout/filters/etools-filters.ts
[ch25257] Standardize Clear all action: remove filters from UI and deselect selected filters from the dropdown
=> [ch25257] Standardize Clear all action: remove filters from UI and deselect selected filters from the dropdown

src_ts/components/pages/assessments/assessment-tab-pages/details/assessing-firm.ts
[ch25663] Firm Name not displayed when logged in with Firm Staff Member with Access
=> [ch25663] Firm Name not displayed when logged in with Firm Staff Member with Access

package-lock.json, package.json, src_ts/components/app-shell/app-shell.ts, src_ts/components/pages/assessments/assessment-tab-pages/details/assessment-info.ts, src_ts/endpoints/endpoints-list.ts, src_ts/redux/actions/common-data.ts, src_ts/redux/reducers/common-data.ts, src_ts/types/assessment.ts
[ch25658] Add 2 new dropdown menus "PSEA assessment type" and "Reason for country-level INGO assessment" to match changes in VISION for 1 July 2021
=> [ch25658] Add 2 new dropdown menus "PSEA assessment type" and "Reason for country-level INGO assessment" to match changes in VISION for 1 July 2021

src_ts/components/common/layout/status/etools-status.ts
=> [ch25880]Responsive status

src_ts/components/common/layout/export-data.ts, src_ts/components/pages/assessments/assessment-tabs.ts
[ch21780] adding additional columns for the export excel sheet of individual assessments
=> [ch21780] adding additional columns for the export excel sheet of individual assessments

package-lock.json, package.json
=> [ch25846]Update app-selector

src_ts/components/pages/assessments/assessment-tabs.ts
[ch15943] Reason for rejection should disappear once the Assessment is in status "Final"
=> [ch15943] Reason for rejection should disappear once the Assessment is in status "Final"

src_ts/components/app-shell/app-theme.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/questionnaire-item.ts
=> [ch26483]Save and Cancel btns still available at submission of Questionnaire if a Core Standard section is open

package-lock.json, package.json, src_ts/components/app-shell/app-shell.ts, src_ts/components/common/toast-notifications/toast-notification-helper.ts
=> [ch27278]Piwik tracking

src_ts/components/app-shell/app-theme.ts, src_ts/components/app-shell/menu/app-menu.ts, src_ts/components/app-shell/menu/styles/nav-menu-styles.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/assessment-questionnaire-page.ts, src_ts/components/styles/label-and-value-styles-lit.ts, src_ts/components/styles/shared-styles-lit.ts, src_ts/config/config.ts
[ch26572] [Accessibility]Ensure that all text contrasts sufficiently with its background when viewed by
=> [ch26572] [Accessibility]Ensure that all text contrasts sufficiently with its background when viewed by

src_ts/components/app-shell/menu/app-menu.ts
[ch26572] [Accessibility] Ensure that all text contrasts sufficiently with its background when viewed by
=> [ch26572] [Accessibility] Ensure that all text contrasts sufficiently with its background when viewed by

src_ts/components/pages/assessments/assessment-tab-pages/follow-up/follow-up-dialog.ts
[ch27584] Incorrect Date validation for "Due on"
=> [ch27584] Incorrect Date validation for "Due on"

package-lock.json, package.json, src_ts/components/app-shell/app-shell.ts, src_ts/components/app-shell/header/page-header.ts
[ch27671] Update tooltip text when hovering over app selector, Support link, user profile, refresh symbol
=> [ch27671] Update tooltip text when hovering over app selector, Support link, user profile, refresh symbol

src_ts/components/pages/assessments/assessment-tab-pages/follow-up/follow-up-dialog.ts
[ch27923] Console error on Edit Action Point
=> [ch27923] Console error on Edit Action Point

src_ts/components/pages/assessments/assessments-list.ts, src_ts/components/utils/utils.ts
[ch28367] Assessments list: Search results incorrectly returned
=> [ch28367] Assessments list: Search results incorrectly returned

src_ts/types/user-model.ts
=> [ch25430]Boolean values coming as string on user profile endpoint

package-lock.json, package.json
[ch28079] Migrate to LitElement etools-profile-dropdown component
=> [ch28079] Migrate to LitElement etools-profile-dropdown component

src_ts/components/pages/assessments/assessments-list.ts
[ch17503] Update Matomo tracking
=> [ch17503] Update Matomo tracking

src_ts/components/pages/assessments/status-transitions/assessment-status-transition-actions.ts
[ch29242] [Automation Support]: Add QA class values or ids in FE
=> [ch29242] [Automation Support]: Add QA class values or ids in FE

src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/answer-instructions.ts, src_ts/components/pages/assessments/assessment-tab-pages/questionnaire/questionnaire-answer.ts
=> [ch30225] Fix tooltip position

src_ts/components/pages/assessments/assessments-list.ts
=> [ch31857]PSEA End of life-remove add

src_ts/components/pages/assessments/assessment-tab-pages/details/assessment-details-page.ts, src_ts/components/pages/assessments/assessment-tabs.ts
=> [ch31857]Fix indirect access

src_ts/components/pages/assessments/assessments-list.ts
=> [ch32263]PSEA end of life - update msg

src_ts/components/app-shell/header/page-header.ts
[ch32541] implement logout with redirect Azure ADB2C with the same effect as the "social/unicef-logout" url has in PRP.
=> [ch32541] implement logout with redirect Azure ADB2C with the same effect as the "social/unicef-logout" url has in PRP.

src_ts/components/pages/assessments/assessments-list.ts
=> [ch34438] fix partner_hact for FM
